name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE_URL: gcr.io/cabby-392012/cabby-service
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-ci:
    name: Run CI Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci 

      - name: Check types
        run: npm run type-check

      - name: Check linting
        run: npm run lint

      - name: Check formatting
        run: npm run format:check

  build-and-deploy-staging:
    environment:
      name: staging
    name: Build and Deploy to Cloud Run (Staging)
    needs: run-ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci 

      - name: Build
        run: npm run build

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Build and push Docker image to GCR (Staging)
        run: | 
          gcloud builds submit --tag ${{ env.IMAGE_URL }}:staging-${{ github.sha }} --project ${{ env.PROJECT_ID }}

      - name: Deploy to Cloud Run (Staging)
        run: |
          gcloud run deploy cabby-admin-staging \
            --image ${{ env.IMAGE_URL }}:staging-${{ github.sha }} \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --project ${{ env.PROJECT_ID }}

  build-and-deploy-production:
    environment:
      name: production
    name: Build and Deploy to Cloud Run (Production)
    needs: run-ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.head_commit.message == '*deploy prod*'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci 

      - name: Build
        run: npm run build

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Build and push Docker image to GCR (Production)
        run: | 
          gcloud builds submit --tag ${{ env.IMAGE_URL }}:production-${{ github.sha }} --project ${{ env.PROJECT_ID }}

      - name: Deploy to Cloud Run (Production)
        run: |
          gcloud run deploy cabby-admin-production \
            --image ${{ env.IMAGE_URL }}:production-${{ github.sha }} \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --project ${{ env.PROJECT_ID }}
